version: '3.9'

services:
  pretrainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REPO_URL: ${GIT_REPO_URL}
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_PASSWORD: ${GIT_PASSWORD}
    env_file:
      - .env 
    
    # privileged: true
    volumes:
      - ${PRETRAINING_INPUT_PATH}:/pretraining/input
      - ${PRETRAINING_OUTPUT_PATH}:/pretraining/output
    ports:
      - "4304:3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]